### ISSUE TITLE
doesn't "commented out" mean that you make some *code* a comment?

### ISSUE THREAD

**Issue by cschaffner** [BasicProbability/PythonCode_Fall2015#1]
http://english.stackexchange.com/questions/33483/when-i-say-comment-out-does-it-mean-to-uncomment-something-or-comment-it

**Comment by philschulz** [comment]
Yes, it does. But the purpose of doing so is that you want to render this code inactive temporarily instead of deleting it right away.

**Comment by philschulz** [comment]
Ah, sorry, now I get your question. Changed this.
